import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";
import { requestStructuredJson } from "@/lib/server/openai-json";
import type {
  AiEngine,
  SourceEvolutionRequest,
  SourceEvolutionResponse,
  SourceEvolutionRule,
  SourceEvolutionSnapshot,
} from "@/lib/types";

export const runtime = "nodejs";

const GENERATED_DIR = path.join(process.cwd(), "src", "generated");
const GENERATED_FILE = path.join(GENERATED_DIR, "eyevolve-learned-rules.ts");
const RELATIVE_FILE = "src/generated/eyevolve-learned-rules.ts";
const SOURCE_VERSION = 1;
const MAX_RULES = 8;

const sourceEvolutionSchema = {
  type: "object",
  additionalProperties: false,
  required: ["summary", "rules"],
  properties: {
    summary: { type: "string", maxLength: 180 },
    rules: {
      type: "array",
      minItems: 1,
      maxItems: 3,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["title", "when", "then"],
        properties: {
          title: { type: "string", maxLength: 72 },
          when: { type: "string", maxLength: 140 },
          then: { type: "string", maxLength: 170 },
        },
      },
    },
  },
};

const fallbackSnapshot = (): SourceEvolutionSnapshot => ({
  version: SOURCE_VERSION,
  updatedAt: new Date().toISOString(),
  summary:
    "Initial generated source subsystem. EYEVOLVE has not written a runtime source mutation yet.",
  rules: [
    {
      id: "gen-1-initial-policy-boundary",
      generation: 1,
      title: "Keep source evolution bounded",
      when: "EYEVOLVE learns from user judgment or autonomous action.",
      then: "Only this generated rules file may change; the main application stays authoritative.",
      source: "local",
    },
  ],
});

const cleanText = (value: unknown, fallback: string, maxLength: number) =>
  typeof value === "string" && value.trim()
    ? value.trim().replace(/\s+/g, " ").slice(0, maxLength)
    : fallback.slice(0, maxLength);

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 44) || "learned-rule";

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const renderSource = (snapshot: SourceEvolutionSnapshot) => `// Generated by EYEVOLVE Source Evolution Lab.
// This is the only source file the runtime is allowed to rewrite.
// Do not hand-edit during a demo; use the EYEVOLVE source evolution route.

import type { SourceEvolutionSnapshot } from "@/lib/types";

export const sourceEvolutionSnapshot: SourceEvolutionSnapshot = ${JSON.stringify(
  snapshot,
  null,
  2,
)};
`;

const extractSnapshot = (source: string): SourceEvolutionSnapshot => {
  const match = source.match(
    /export const sourceEvolutionSnapshot: SourceEvolutionSnapshot = ([\s\S]*?);\s*$/m,
  );
  if (!match) {
    return fallbackSnapshot();
  }

  try {
    const parsed = JSON.parse(match[1]) as SourceEvolutionSnapshot;
    if (
      parsed.version !== SOURCE_VERSION ||
      !Array.isArray(parsed.rules) ||
      typeof parsed.summary !== "string"
    ) {
      return fallbackSnapshot();
    }
    return parsed;
  } catch {
    return fallbackSnapshot();
  }
};

const readCurrentSource = async () => {
  try {
    return await readFile(GENERATED_FILE, "utf8");
  } catch {
    return renderSource(fallbackSnapshot());
  }
};

const buildDiff = (beforeSource: string, afterSource: string) => {
  if (beforeSource === afterSource) {
    return "No source changes.";
  }

  const beforeLines = beforeSource.trimEnd().split("\n");
  const afterLines = afterSource.trimEnd().split("\n");
  const prefix: string[] = [
    `--- a/${RELATIVE_FILE}`,
    `+++ b/${RELATIVE_FILE}`,
    "@@ generated source subsystem @@",
  ];

  return [
    ...prefix,
    ...beforeLines.map((line) => `-${line}`),
    ...afterLines.map((line) => `+${line}`),
  ].join("\n");
};

const localProposal = (body: SourceEvolutionRequest) => {
  const primaryAction = body.event.learnedRule || body.event.summary;
  const latestAction = body.scene.recommendedAction ?? "update the learned response";
  return {
    summary: `Source rule evolved from ${body.event.sceneTitle}.`,
    rules: [
      {
        title: `Gen ${body.event.generation}: ${body.scene.title}`,
        when: primaryAction,
        then: `Prefer to ${latestAction.toLowerCase()} when similar evidence appears again.`,
      },
    ],
  };
};

const validateProposal = (
  value: unknown,
  body: SourceEvolutionRequest,
  engine: AiEngine,
): { summary: string; rules: SourceEvolutionRule[] } | null => {
  if (!isRecord(value) || !Array.isArray(value.rules)) {
    return null;
  }

  const rules = value.rules
    .filter(isRecord)
    .slice(0, 3)
    .map((rule, index) => {
      const title = cleanText(
        rule.title,
        `Gen ${body.event.generation} learned behavior`,
        72,
      );
      return {
        id: `gen-${body.event.generation}-${slugify(title)}-${index + 1}`,
        generation: body.event.generation,
        title,
        when: cleanText(rule.when, body.event.learnedRule, 140),
        then: cleanText(rule.then, body.event.summary, 170),
        source: engine,
      };
    });

  if (!rules.length) {
    return null;
  }

  return {
    summary: cleanText(
      value.summary,
      `Source rule evolved from ${body.event.sceneTitle}.`,
      180,
    ),
    rules,
  };
};

const evolveSource = async (
  body: SourceEvolutionRequest,
): Promise<SourceEvolutionResponse> => {
  const beforeSource = await readCurrentSource();
  const current = extractSnapshot(beforeSource);

  const parsed = await requestStructuredJson({
    promptFile: "source-evolution.md",
    schemaName: "eyevolve_source_evolution",
    schema: sourceEvolutionSchema,
    input: {
      instruction:
        "Propose a small update for the generated source rules subsystem.",
      event: {
        generation: body.event.generation,
        sceneTitle: body.event.sceneTitle,
        summary: body.event.summary,
        learnedRule: body.event.learnedRule,
        reasoningSummary: body.event.reasoningSummary,
        nextLearningObjective: body.event.nextLearningObjective,
      },
      scene: {
        id: body.scene.id,
        title: body.scene.title,
        scenarioType: body.scene.scenarioType,
        recommendedAction: body.scene.recommendedAction,
        actionService: body.scene.actionService,
        changes: body.scene.changes.map((change) => ({
          id: change.id,
          label: change.label,
          description: change.description,
          suggestedAction: change.suggestedAction,
          noiseCandidate: change.noiseCandidate,
        })),
      },
      policy: body.state.policy,
      recentHistory: body.state.evolutionHistory.slice(-5).map((event) => ({
        generation: event.generation,
        sceneTitle: event.sceneTitle,
        summary: event.summary,
        learnedRule: event.learnedRule,
      })),
      currentGeneratedRules: current.rules,
    },
  });

  const engine: AiEngine = parsed ? "openai" : "local";
  const proposal =
    validateProposal(parsed, body, engine) ??
    validateProposal(localProposal(body), body, "local");

  const nextSnapshot: SourceEvolutionSnapshot = {
    version: SOURCE_VERSION,
    updatedAt: new Date().toISOString(),
    summary:
      proposal?.summary ??
      `Source rule evolved from ${body.event.sceneTitle}.`,
    rules: [
      ...current.rules,
      ...(proposal?.rules ?? []),
    ].slice(-MAX_RULES),
  };

  const afterSource = renderSource(nextSnapshot);
  await mkdir(GENERATED_DIR, { recursive: true });
  await writeFile(GENERATED_FILE, afterSource, "utf8");

  return {
    engine: proposal?.rules.some((rule) => rule.source === "openai")
      ? "openai"
      : "local",
    filePath: RELATIVE_FILE,
    summary: nextSnapshot.summary,
    beforeSource,
    afterSource,
    diff: buildDiff(beforeSource, afterSource),
    snapshot: nextSnapshot,
  };
};

export async function GET() {
  const source = await readCurrentSource();
  return NextResponse.json({
    engine: "local",
    filePath: RELATIVE_FILE,
    summary: extractSnapshot(source).summary,
    beforeSource: source,
    afterSource: source,
    diff: "No source changes.",
    snapshot: extractSnapshot(source),
  } satisfies SourceEvolutionResponse);
}

export async function POST(request: Request) {
  const body = (await request.json()) as SourceEvolutionRequest;
  return NextResponse.json(await evolveSource(body));
}
